SELECT customer_id, first_name, last_name, phone, email, street, city, state, zip_code FROM
sales.customers;
SELECT CUSTOMER_ID, PHONE, EMAIL FROM
SALES.CUSTOMERS;

SELECT order_id, customer_id, order_status, order_date, required_date, shipped_date, store_id, staff_id from
sales.orders;
SELECT STORE_ID, PRODUCT_ID, QUANTITY FROM
PRODUCTION.STOCKS;
SELECT * FROM PRODUCTION.STOCKS;
SELECT * FROM DBO.CUSTOMERS;
SELECT CUSTOMERID, COMPANYNAME, CONTACTNAME, CONTACTTITLE, ADDRESS, CITY, REGION, POSTALCODE, COUNTRY, PHONE, FAX FROM
DBO.CUSTOMERS;
------------- WHERE QUERY HEREGLEHED WHERE SONGOLT = ' TEGEED NER' 
SELECT * FROM DBO.CUSTOMERS
WHERE COUNTRY = 'MEXICO'

SELECT CUSTOMERID, COMPANYNAME, CONTACTNAME, COUNTRY FROM
DBO.CUSTOMERS
WHERE COUNTRY = 'USA'

SELECT CUSTOMERID, COMPANYNAME, CONTACTNAME, COUNTRY FROM DBO.CUSTOMERS
WHERE COMPANYNAME = 'AMAZON'

SELECT CUSTOMERID, CONTACTNAME, CONTACTTITLE FROM DBO.CUSTOMERS
WHERE CONTACTTITLE = 'MANAGER'

SELECT CUSTOMERID, ADDRESS, CITY FROM DBO.CUSTOMERS
WHERE POSTALCODE = '05023'
--------- 
SELECT CUSTOMERID, ADDRESS, CITY FROM DBO.CUSTOMERS
WHERE CITY = 'VA'

SELECT CUSTOMERID, CONTACTNAME, CONTACTTITLE, CITY, PHONE FROM DBO.CUSTOMERS
WHERE CITY = 'ARLINGTON'

SELECT * FROM DBO.CUSTOMERS
WHERE CITY = 'ARLINGTON'
SELECT * FROM SALES.CUSTOMERS
WHERE STATE = 'NY'
SELECT * FROM SALES.CUSTOMERS
WHERE STATE = 'CA'
SELECT * FROM SALES.CUSTOMERS
WHERE CITY = 'BUFFALO'
SELECT * FROM SALES.CUSTOMERS
WHERE CITY = 'CAMPBELL'